services:
  backend:
    build:
      context: ./quiz-backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    ports:
      - "8080:8080"
    networks:
      - quiz-network
    restart: always

  frontend:
    build:
      context: ./quiz-frontend
      dockerfile: Dockerfile
    container_name: quiz-frontend
    ports:
      - "80:80"
    networks:
      - quiz-network
    depends_on:
      - backend
    restart: always

networks:
  quiz-network:
    driver: bridge

